# Analysis from cell death quantification
# 22.03.2022
# Daniel Moser
# Data was generated by Maurice König
# Comparison of the effect of different peptide treatments on the cell death caused by Botrytis

# Load packages
library(tidyverse)
library(multcompView)

# Load data
test_data <- read_tsv("botrytis/botrytis lehsion size all reps final.txt")
replicate <- seq(1,78)
test_data <- cbind(test_data, replicate)
test_data %>% pivot_longer(!replicate, names_to = "treatment") -> data
data$treatment <- factor(data$treatment,
                    levels=c("mock",
                                       "chitin",
                                       "flg22",
                                       "Zip1",
                                       "IRP",
                                       "PSK1",
                                       "PIP1",
                                       "AMP1"))

# ANOVA - within group variation
model_td <- lm(value ~ treatment, data)
anova_td <- aov(model_td) # ANOVA table


# Tukey HSD - comparison of treatments
tukey_td <- TukeyHSD(anova_td, conf.level = 0.95, ordered = T)
tukey_td$treatment

# Group letter display
letter_colors <- list("a" = "blue",
                      "ab" = "brown",
                      "bc" = "green",
                      "c" = "orange",
                      "d" = "red",
                      "e" = "pink")
group_letters <- as.data.frame.list(multcompLetters4(anova_td, tukey_td)$treatment)[1]
group_letters <- tibble(treatment=row.names(group_letters),
                        letters=group_letters$Letters)
data %>% 
  left_join(group_letters, by="treatment") %>%
  mutate(color_letter = as.character(letter_colors[letters])) -> data

  
data %>% 
  group_by(treatment) %>% 
  summarise(position = max(value, na.rm	= T) * 1.10,
            avg = mean(value, na.rm	= T)) %>% 
  left_join(group_letters, by="treatment") %>%
  mutate(color_letter = as.character(letter_colors[letters])) -> position_data

position_data$treatment <- factor(position_data$treatment,
                                  levels=c("mock",
                                           "chitin",
                                           "flg22",
                                           "Zip1",
                                           "IRP",
                                           "PSK1",
                                           "PIP1",
                                           "AMP1"))


# Plotting
g <- ggplot(data, aes(treatment, value)) +
      geom_text(data=position_data, aes(x= treatment, y = 1.7, label = letters), size = 3, fontface="bold") +
      xlab("Treatment") + 
      ylab("Lesion area cm^2") +
      scale_y_continuous(breaks=c(seq(0, 1.6, by=0.2))) +
      theme_classic() +
      theme(plot.title = element_text(vjust = 1, hjust = 0.5, size = 16, face="bold"),
          axis.title = element_text(size = 10, face="bold"),
          axis.title.x = element_text(vjust = 0),
          axis.title.y = element_text(vjust = 2),
          axis.text = element_text(size = 8)) +
  geom_boxplot(data=data, aes(treatment, value), outlier.colour = NA, 
               fill=c("#a4a4a4", "#fae4d5", "#f3af82", "#e1efd7", "#c3dfb3", "#a6cf8b", "#538037", "#bdbdbd")) +
  geom_jitter(data=data, aes(treatment, value), col="black", width=0.2, size=0.7, shape=1) + 
  geom_point(data=position_data, aes(x=treatment, y=avg), shape=3, size=7, stroke=0.9) +
  theme(legend.position="none")
g

test <- anova(model_td)
test$`Pr(>F)`[1]

